/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.boton;

/**
 *
 * @author TheGr
 */
public class OpcionesPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form OpcionesPrincipal
     */
    public OpcionesPrincipal() {
        initComponents();
    }
    public void configurarBoton(String texto, String iconoNombre){
        txtCategoria.setText(texto);
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+iconoNombre+".png"))); // NOI18N
        txtImagen.setText(" ");
    }
    public void posicionar(int x, int y){
        setBounds(x, y, getBounds().width, getBounds().height);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtImagen = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JLabel();
        linea = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(82, 82, 82));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(193, 176));
        setPreferredSize(new java.awt.Dimension(193, 176));

        txtImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paciente.png"))); // NOI18N
        txtImagen.setText(" ");

        txtCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCategoria.setText("texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(linea, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator linea;
    private javax.swing.JLabel txtCategoria;
    private javax.swing.JLabel txtImagen;
    // End of variables declaration//GEN-END:variables
}
