/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import modelo.ModeloBD;
import vista.altas.AccionConfigurable;

import java.awt.*;

/**
 *
 * @author TheGr
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombreTabla = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(1010, 620));
        setPreferredSize(new java.awt.Dimension(1010, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(62, 62, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 20));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreTabla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNombreTabla.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreTabla.setText("L");
        jPanel1.add(txtNombreTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 640, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de registros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 40, 640, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 66));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultar.setBackground(new java.awt.Color(112, 112, 112));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(168, 199, 255));
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setBorder(null);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 80));

        btnModificar.setBackground(new java.awt.Color(112, 112, 112));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 226, 163));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(null);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 80));

        btnEliminar.setBackground(new java.awt.Color(112, 112, 112));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 207, 207));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 80));

        btnAgregar.setBackground(new java.awt.Color(112, 112, 112));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(132, 255, 160));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 80));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 560));

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDatos.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tablaDatos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 690, 490));
    }// </editor-fold>//GEN-END:initComponents
    
    public void configurarBotonAgregar(){
        btnAgregar.setVisible(true);
    }
    public void configurarBotonEliminar(){

        btnEliminar.setVisible(true);
    }
    public void configurarBotonModificar(){

        btnModificar.setVisible(true);
    }
    public void configurarBotonConsultar(){

        btnConsultar.setVisible(true);
        System.out.println("nostrao");
    }
    public void ocultarBotones(){
        System.out.println("oculto");
        btnAgregar.setVisible(false);
        btnEliminar.setVisible(false);
        btnModificar.setVisible(false);
        btnConsultar.setVisible(false);
    }
    public void configurarTabla(){
        Componedor.columnasTabla(tablaDatos, tabla);
    }
    public void encabezado(String texto){
        tabla = texto;
        txtNombreTabla.setText(texto);
    }
    public void nombreTabla(String texto){
        tabla = texto;
    }
    public void setDisplay(String texto){
        display = texto;
    }
    public void agregarRegistro(Object[] r){
        ((DefaultTableModel)tablaDatos.getModel()).addRow(r);
    }
    private void revisarVentana(JFrame v)
    {
        if(!v.isVisible()){
            v.setVisible(true);
        }
    }
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if(ventanaConsultar == null || (ventanaConsultar!= null && ventanaConsultar.getNombreTabla() != tabla)) {
            ventanaConsultar = new AccionConfigurable();
            ventanaConsultar.configurarLabel(display);
            ventanaConsultar.nombreTabla(tabla);
            ventanaConsultar.configurarTabla();
            System.out.println(tabla);
            //en teoria cada tabla podria hacerlo solita
            ventanaConsultar.datosGeneracion(
                    ModeloBD.labelsDe(tabla),
                    ModeloBD.compsDe(tabla),
                    ModeloBD.obtenerTiposSQL(tabla),
                    ModeloBD.longDe(tabla),
                    ModeloBD.nnlDe(tabla),
                    null
            );
            ventanaConsultar.generar();
            ventanaConsultar.activarPK();
            ventanaConsultar.configurarBotonPrimario((byte)3, "Consultar", new Color(255, 255, 255), new Color(58, 114, 255));
        }
        revisarVentana(ventanaConsultar);
        revisarVentana(ventanaConsultar);
    }//GEN-LAST:event_btnConsultarActionPerformed

    //generacion o re-apertura de la ventana
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if(ventanaAgregar == null || (ventanaAgregar!= null && ventanaAgregar.getNombreTabla() != tabla)) {
            ventanaAgregar = new AccionConfigurable();
            ventanaAgregar.configurarLabel(display);
            ventanaAgregar.nombreTabla(tabla);
            ventanaAgregar.configurarTabla();
            System.out.println(tabla);
            //en teoria cada tabla podria hacerlo solita
            ventanaAgregar.datosGeneracion(
                    ModeloBD.labelsDe(tabla),
                    ModeloBD.compsDe(tabla),
                    ModeloBD.obtenerTiposSQL(tabla),
                    ModeloBD.longDe(tabla),
                    ModeloBD.nnlDe(tabla),
                    null
            );
            ventanaAgregar.generar();
            ventanaAgregar.activarPK();
            ventanaAgregar.configurarBotonPrimario((byte)0, "Agregar", new Color(51, 102, 255), new Color(255, 255, 255));
        }
        revisarVentana(ventanaAgregar);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(ventanaEliminar == null || (ventanaEliminar!= null && ventanaEliminar.getNombreTabla() != tabla)) {
            ventanaEliminar = new AccionConfigurable();
            ventanaEliminar.configurarLabel(display);
            ventanaEliminar.nombreTabla(tabla);
            ventanaEliminar.configurarTabla();
            System.out.println(tabla);
            //en teoria cada tabla podria hacerlo solita
            ventanaEliminar.datosGeneracion(
                    ModeloBD.labelsDe(tabla),
                    ModeloBD.compsDe(tabla),
                    ModeloBD.obtenerTiposSQL(tabla),
                    ModeloBD.longDe(tabla),
                    ModeloBD.nnlDe(tabla),
                    null
            );
            ventanaEliminar.generar();
            ventanaEliminar.activarPK();
            ventanaEliminar.configurarBotonPrimario((byte)1, "Eliminar", new Color(255, 51, 51), new Color(255, 255, 255));
        }
        revisarVentana(ventanaEliminar);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(ventanaModificar == null || (ventanaModificar!= null && ventanaModificar.getNombreTabla() != tabla)) {
            ventanaModificar = new AccionConfigurable();
            ventanaModificar.configurarLabel(display);
            ventanaModificar.nombreTabla(tabla);
            ventanaModificar.configurarTabla();
            System.out.println(tabla);
            //en teoria cada tabla podria hacerlo solita
            ventanaModificar.datosGeneracion(
                    ModeloBD.labelsDe(tabla),
                    ModeloBD.compsDe(tabla),
                    ModeloBD.obtenerTiposSQL(tabla),
                    ModeloBD.longDe(tabla),
                    ModeloBD.nnlDe(tabla),
                    null
            );
            ventanaModificar.generar();
            ventanaModificar.activarPK();
            ventanaModificar.configurarBotonPrimario((byte)2, "Modificar", new Color(255, 221, 51), new Color(255, 255, 255));
        }
        revisarVentana(ventanaModificar);
    }//GEN-LAST:event_btnModificarActionPerformed

    private String display;
    private String tabla;
    private AccionConfigurable ventanaAgregar;
    private AccionConfigurable ventanaEliminar;
    private AccionConfigurable ventanaModificar;
    private AccionConfigurable ventanaConsultar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JLabel txtNombreTabla;
    // End of variables declaration//GEN-END:variables
}
