/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexionBD.ConexionBDLite;
import controlador.DAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.*;
import reportes.Reportador;


/**
 *
 * @author TheGr
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ConexionBDLite conector = ConexionBDLite.obtenerConector();
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRoot = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnPrincipal = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnReportes = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnVistas = new javax.swing.JButton();
        panelControl = new javax.swing.JPanel();
        panelPacientes = new javax.swing.JPanel();
        txtPacientes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        panelMedicos = new javax.swing.JPanel();
        txtMedicos = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        panelFarmacias = new javax.swing.JPanel();
        txtFarmacias = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        panelFarmaceuticas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtFarmaceuticas2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelRecetas = new javax.swing.JPanel();
        txtRecetas = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        panelInventarios = new javax.swing.JPanel();
        txtRecetas1 = new javax.swing.JLabel();
        txtRecetas2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        panelContratos = new javax.swing.JPanel();
        txtRecetas3 = new javax.swing.JLabel();
        txtRecetas4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        panelMedicamentos = new javax.swing.JPanel();
        txtRecetas5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuReportes = new javax.swing.JMenu();
        rptMedico = new javax.swing.JMenuItem();
        rptPaciente = new javax.swing.JMenuItem();
        rptFarmacia = new javax.swing.JMenuItem();
        rptFarmaceuticas = new javax.swing.JMenuItem();
        rptRecetas = new javax.swing.JMenuItem();
        rptInventarios = new javax.swing.JMenuItem();
        rptContratos = new javax.swing.JMenuItem();
        rptMedicamentos = new javax.swing.JMenuItem();
        menuVistas = new javax.swing.JMenu();
        viewSupervisores = new javax.swing.JMenuItem();
        menuEstadisticas = new javax.swing.JMenu();
        chartDemanda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Panel de control");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelRoot.setBackground(new java.awt.Color(255, 255, 255));
        panelRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipal.setBackground(new java.awt.Color(80, 80, 80));
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPrincipalMouseReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setMinimumSize(new java.awt.Dimension(7, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(6, 100));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Abrir panel principal");

        javax.swing.GroupLayout btnPrincipalLayout = new javax.swing.GroupLayout(btnPrincipal);
        btnPrincipal.setLayout(btnPrincipalLayout);
        btnPrincipalLayout.setHorizontalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPrincipalLayout.setVerticalGroup(
            btnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPrincipalLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, -1));

        btnUsuarios.setBackground(new java.awt.Color(80, 80, 80));

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));
        jPanel6.setMinimumSize(new java.awt.Dimension(7, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(6, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuarios");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnUsuariosLayout = new javax.swing.GroupLayout(btnUsuarios);
        btnUsuarios.setLayout(btnUsuariosLayout);
        btnUsuariosLayout.setHorizontalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuariosLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUsuariosLayout.setVerticalGroup(
            btnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, Short.MAX_VALUE)
        );

        jPanel3.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, -1));

        btnLogout.setBackground(new java.awt.Color(80, 80, 80));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogoutMouseReleased(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(0, 153, 204));
        jPanel7.setMinimumSize(new java.awt.Dimension(7, 100));
        jPanel7.setPreferredSize(new java.awt.Dimension(6, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Salir");

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 200, 70));

        panelRoot.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 680));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReportes.setBackground(new java.awt.Color(0, 153, 255));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Menú");
        btnReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        btnEstadisticas.setBackground(new java.awt.Color(0, 153, 255));
        btnEstadisticas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        btnEstadisticas.setText("Estadísticas");
        btnEstadisticas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        jPanel2.add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 148, 60));

        btnVistas.setBackground(new java.awt.Color(0, 153, 255));
        btnVistas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVistas.setForeground(new java.awt.Color(255, 255, 255));
        btnVistas.setText("Vistas");
        btnVistas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 148, 60));

        panelRoot.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1010, 60));

        panelControl.setBackground(new java.awt.Color(102, 102, 102));

        panelPacientes.setBackground(new java.awt.Color(82, 82, 82));
        panelPacientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelPacientes.setForeground(new java.awt.Color(255, 255, 255));
        panelPacientes.setPreferredSize(new java.awt.Dimension(193, 176));
        panelPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelPacientesMouseReleased(evt);
            }
        });

        txtPacientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPacientes.setForeground(new java.awt.Color(255, 255, 255));
        txtPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPacientes.setText("Registro de pacientes");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paciente.png"))); // NOI18N

        javax.swing.GroupLayout panelPacientesLayout = new javax.swing.GroupLayout(panelPacientes);
        panelPacientes.setLayout(panelPacientesLayout);
        panelPacientesLayout.setHorizontalGroup(
            panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelPacientesLayout.setVerticalGroup(
            panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPacientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMedicos.setBackground(new java.awt.Color(82, 82, 82));
        panelMedicos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelMedicos.setForeground(new java.awt.Color(255, 255, 255));
        panelMedicos.setPreferredSize(new java.awt.Dimension(193, 176));
        panelMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMedicosMouseReleased(evt);
            }
        });

        txtMedicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMedicos.setForeground(new java.awt.Color(255, 255, 255));
        txtMedicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMedicos.setText("Médicos activos");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medico.png"))); // NOI18N

        javax.swing.GroupLayout panelMedicosLayout = new javax.swing.GroupLayout(panelMedicos);
        panelMedicos.setLayout(panelMedicosLayout);
        panelMedicosLayout.setHorizontalGroup(
            panelMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMedicosLayout.setVerticalGroup(
            panelMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelFarmacias.setBackground(new java.awt.Color(82, 82, 82));
        panelFarmacias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelFarmacias.setForeground(new java.awt.Color(255, 255, 255));
        panelFarmacias.setPreferredSize(new java.awt.Dimension(193, 176));
        panelFarmacias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelFarmaciasMouseReleased(evt);
            }
        });

        txtFarmacias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFarmacias.setForeground(new java.awt.Color(255, 255, 255));
        txtFarmacias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFarmacias.setText("Sucursales");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/farmacia.png"))); // NOI18N

        javax.swing.GroupLayout panelFarmaciasLayout = new javax.swing.GroupLayout(panelFarmacias);
        panelFarmacias.setLayout(panelFarmaciasLayout);
        panelFarmaciasLayout.setHorizontalGroup(
            panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFarmaciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFarmacias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFarmaciasLayout.setVerticalGroup(
            panelFarmaciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFarmaciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFarmacias, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelFarmaceuticas.setBackground(new java.awt.Color(82, 82, 82));
        panelFarmaceuticas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelFarmaceuticas.setForeground(new java.awt.Color(255, 255, 255));
        panelFarmaceuticas.setPreferredSize(new java.awt.Dimension(193, 176));
        panelFarmaceuticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelFarmaceuticasMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Farmacéuticas");

        txtFarmaceuticas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFarmaceuticas2.setForeground(new java.awt.Color(255, 255, 255));
        txtFarmaceuticas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFarmaceuticas2.setText("afiliadas");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/farmaceutica.png"))); // NOI18N

        javax.swing.GroupLayout panelFarmaceuticasLayout = new javax.swing.GroupLayout(panelFarmaceuticas);
        panelFarmaceuticas.setLayout(panelFarmaceuticasLayout);
        panelFarmaceuticasLayout.setHorizontalGroup(
            panelFarmaceuticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFarmaceuticasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFarmaceuticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFarmaceuticas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFarmaceuticasLayout.setVerticalGroup(
            panelFarmaceuticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFarmaceuticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFarmaceuticas2)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(62, 62, 62));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Seleccione una de las siguientes categorías");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRecetas.setBackground(new java.awt.Color(82, 82, 82));
        panelRecetas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelRecetas.setForeground(new java.awt.Color(255, 255, 255));
        panelRecetas.setPreferredSize(new java.awt.Dimension(193, 176));
        panelRecetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelRecetasMouseReleased(evt);
            }
        });

        txtRecetas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecetas.setForeground(new java.awt.Color(255, 255, 255));
        txtRecetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRecetas.setText("Historial de recetas");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receta.png"))); // NOI18N

        javax.swing.GroupLayout panelRecetasLayout = new javax.swing.GroupLayout(panelRecetas);
        panelRecetas.setLayout(panelRecetasLayout);
        panelRecetasLayout.setHorizontalGroup(
            panelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtRecetas, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRecetasLayout.setVerticalGroup(
            panelRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelInventarios.setBackground(new java.awt.Color(82, 82, 82));
        panelInventarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelInventarios.setForeground(new java.awt.Color(255, 255, 255));
        panelInventarios.setPreferredSize(new java.awt.Dimension(193, 176));
        panelInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelInventariosMouseReleased(evt);
            }
        });

        txtRecetas1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecetas1.setForeground(new java.awt.Color(255, 255, 255));
        txtRecetas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRecetas1.setText("Inventarios de");

        txtRecetas2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecetas2.setForeground(new java.awt.Color(255, 255, 255));
        txtRecetas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRecetas2.setText("farmacias");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N

        javax.swing.GroupLayout panelInventariosLayout = new javax.swing.GroupLayout(panelInventarios);
        panelInventarios.setLayout(panelInventariosLayout);
        panelInventariosLayout.setHorizontalGroup(
            panelInventariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInventariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRecetas1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtRecetas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jSeparator6)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInventariosLayout.setVerticalGroup(
            panelInventariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecetas1)
                .addGap(3, 3, 3)
                .addComponent(txtRecetas2)
                .addContainerGap())
        );

        panelContratos.setBackground(new java.awt.Color(82, 82, 82));
        panelContratos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelContratos.setForeground(new java.awt.Color(255, 255, 255));
        panelContratos.setPreferredSize(new java.awt.Dimension(193, 176));
        panelContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelContratosMouseReleased(evt);
            }
        });

        txtRecetas3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecetas3.setForeground(new java.awt.Color(255, 255, 255));
        txtRecetas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRecetas3.setText("Contratos con");

        txtRecetas4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecetas4.setForeground(new java.awt.Color(255, 255, 255));
        txtRecetas4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRecetas4.setText("farmacéuticas");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contrato.png"))); // NOI18N

        javax.swing.GroupLayout panelContratosLayout = new javax.swing.GroupLayout(panelContratos);
        panelContratos.setLayout(panelContratosLayout);
        panelContratosLayout.setHorizontalGroup(
            panelContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRecetas3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtRecetas4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jSeparator7)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelContratosLayout.setVerticalGroup(
            panelContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContratosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecetas3)
                .addGap(3, 3, 3)
                .addComponent(txtRecetas4)
                .addContainerGap())
        );

        panelMedicamentos.setBackground(new java.awt.Color(82, 82, 82));
        panelMedicamentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 3, true));
        panelMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        panelMedicamentos.setPreferredSize(new java.awt.Dimension(193, 176));
        panelMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMedicamentosMouseReleased(evt);
            }
        });

        txtRecetas5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRecetas5.setForeground(new java.awt.Color(255, 255, 255));
        txtRecetas5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRecetas5.setText("Medicamentos");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contrato.png"))); // NOI18N

        javax.swing.GroupLayout panelMedicamentosLayout = new javax.swing.GroupLayout(panelMedicamentos);
        panelMedicamentos.setLayout(panelMedicamentosLayout);
        panelMedicamentosLayout.setHorizontalGroup(
            panelMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedicamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRecetas5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jSeparator8)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMedicamentosLayout.setVerticalGroup(
            panelMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMedicamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecetas5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFarmacias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFarmaceuticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFarmaceuticas, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(panelPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(panelMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(panelFarmacias, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelContratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        panelRoot.add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 1010, 620));

        getContentPane().add(panelRoot);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setOpaque(true);

        menuReportes.setBackground(new java.awt.Color(0, 153, 255));
        menuReportes.setText("Reportes");

        rptMedico.setBackground(new java.awt.Color(0, 153, 255));
        rptMedico.setForeground(new java.awt.Color(255, 255, 255));
        rptMedico.setText("Medicos");
        rptMedico.setOpaque(true);
        rptMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptMedicoActionPerformed(evt);
            }
        });
        menuReportes.add(rptMedico);

        rptPaciente.setBackground(new java.awt.Color(0, 153, 255));
        rptPaciente.setForeground(new java.awt.Color(255, 255, 255));
        rptPaciente.setText("Pacientes");
        rptPaciente.setOpaque(true);
        rptPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptPacienteActionPerformed(evt);
            }
        });
        menuReportes.add(rptPaciente);

        rptFarmacia.setBackground(new java.awt.Color(0, 153, 255));
        rptFarmacia.setForeground(new java.awt.Color(255, 255, 255));
        rptFarmacia.setText("Farmacias");
        rptFarmacia.setOpaque(true);
        rptFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptFarmaciaActionPerformed(evt);
            }
        });
        menuReportes.add(rptFarmacia);

        rptFarmaceuticas.setBackground(new java.awt.Color(0, 153, 255));
        rptFarmaceuticas.setForeground(new java.awt.Color(255, 255, 255));
        rptFarmaceuticas.setText("Farmaceuticas");
        rptFarmaceuticas.setOpaque(true);
        rptFarmaceuticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptFarmaceuticasActionPerformed(evt);
            }
        });
        menuReportes.add(rptFarmaceuticas);

        rptRecetas.setBackground(new java.awt.Color(0, 153, 255));
        rptRecetas.setForeground(new java.awt.Color(255, 255, 255));
        rptRecetas.setText("Recetas");
        rptRecetas.setOpaque(true);
        rptRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptRecetasActionPerformed(evt);
            }
        });
        menuReportes.add(rptRecetas);

        rptInventarios.setBackground(new java.awt.Color(0, 153, 255));
        rptInventarios.setForeground(new java.awt.Color(255, 255, 255));
        rptInventarios.setText("Inventarios");
        rptInventarios.setOpaque(true);
        rptInventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptInventariosActionPerformed(evt);
            }
        });
        menuReportes.add(rptInventarios);

        rptContratos.setBackground(new java.awt.Color(0, 153, 255));
        rptContratos.setForeground(new java.awt.Color(255, 255, 255));
        rptContratos.setText("Contratos");
        rptContratos.setOpaque(true);
        rptContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptContratosActionPerformed(evt);
            }
        });
        menuReportes.add(rptContratos);

        rptMedicamentos.setBackground(new java.awt.Color(0, 153, 255));
        rptMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        rptMedicamentos.setText("Medicamentos");
        rptMedicamentos.setOpaque(true);
        rptMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptMedicamentosActionPerformed(evt);
            }
        });
        menuReportes.add(rptMedicamentos);

        jMenuBar1.add(menuReportes);

        menuVistas.setBackground(new java.awt.Color(0, 153, 255));
        menuVistas.setText("Vistas");

        viewSupervisores.setBackground(new java.awt.Color(0, 153, 255));
        viewSupervisores.setForeground(new java.awt.Color(255, 255, 255));
        viewSupervisores.setText("Medicamentos por contrato");
        viewSupervisores.setOpaque(true);
        viewSupervisores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupervisoresActionPerformed(evt);
            }
        });
        menuVistas.add(viewSupervisores);

        jMenuBar1.add(menuVistas);

        menuEstadisticas.setText("Estadísticas");

        chartDemanda.setBackground(new java.awt.Color(0, 153, 255));
        chartDemanda.setForeground(new java.awt.Color(255, 255, 255));
        chartDemanda.setText("Demanda de medicamentos");
        chartDemanda.setOpaque(true);
        chartDemanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartDemandaActionPerformed(evt);
            }
        });
        menuEstadisticas.add(chartDemanda);

        jMenuBar1.add(menuEstadisticas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        menuEstadisticas.doClick();
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnPrincipalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMouseReleased
        System.out.println("devolver al panel principal");
        mostrarControl(true);
        mostrarPanel(false);
    }//GEN-LAST:event_btnPrincipalMouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        System.out.println("Regresar al login");
    }//GEN-LAST:event_jPanel3MouseReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //new VentanaLogin().setVisible(true);
    }//GEN-LAST:event_formWindowClosed
    public void activar(Usuario user){
        this.user = user;
        setVisible(true);

        if(user.creaUsuarios == 0) btnUsuarios.setVisible(false);
    }
    private void mostrarControl(boolean b){
        panelControl.setVisible(b);
        panelControl.setEnabled(b);
        if(b)panelBotones.ocultarBotones();
    }
    private void mostrarPanel(boolean b){
        
        panelBotones.setVisible(b);
        panelBotones.setEnabled(b);
    }
    private void configurarPanelBotones(String encabezado, JFrame agregar, JFrame eliminar, JFrame modificar, JFrame consultar, String tabla){
        if(panelBotones == null){
            panelBotones = new PanelBotones();
            panelRoot.add(panelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 1010, 620));
            System.out.println("panel creado");
            panelBotones.ocultarBotones();
        }

        panelBotones.encabezado(encabezado);
        panelBotones.nombreTabla(tabla);
        System.out.println(user.consulta);
        if(user.inserta == 1) panelBotones.configurarBotonAgregar();
        if(user.elimina == 1) panelBotones.configurarBotonEliminar();
        if(user.actualiza == 1) panelBotones.configurarBotonModificar();
        if(user.consulta == 1) panelBotones.configurarBotonConsultar();
        //darle los campos de la tabla sacados de su respectivo registrable
        
    }
    private void panelPacientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPacientesMouseReleased
        System.out.println("configurar tabla pacientes y botones");
        configurarPanelBotones("Control de pacientes", null, null, null, null, "Paciente");
        //conector.prepararStatement("SELECT * FROM BranchNo", null, null);
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos del paciente");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelPacientesMouseReleased
    
    private void panelMedicosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMedicosMouseReleased
        System.out.println("configurar tabla medicos y botones");
        configurarPanelBotones("Control de medicos", null, null, null, null, "Medico");
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos del personal");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelMedicosMouseReleased

    private void panelFarmaciasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFarmaciasMouseReleased
        
        configurarPanelBotones("Control de farmacias", null, null, null, null, "Farmacia");
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos de farmacia");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelFarmaciasMouseReleased

    private void panelFarmaceuticasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFarmaceuticasMouseReleased
        
        configurarPanelBotones("Control de farmaceuticas", null, null, null, null, "Farmaceutica");
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos de farmaceutica");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelFarmaceuticasMouseReleased

    private void panelRecetasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRecetasMouseReleased
        
        configurarPanelBotones("Control de recetas", null, null, null, null, "Recetas");
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos de la receta");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelRecetasMouseReleased

    private void panelInventariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInventariosMouseReleased
        
        configurarPanelBotones("Control de inventarios", null, null, null, null, "Farmacia_Inventario");
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos del inventario");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelInventariosMouseReleased

    private void panelContratosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContratosMouseReleased

        configurarPanelBotones("Control de contratos", null, null, null, null, "Farmacia_Contrato_Farmaceutica");
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos del contrato");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelContratosMouseReleased

    private void btnLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseReleased
        dispose();
        conector.cerrarConexion();
        new VentanaLogin().setVisible(true);
    }//GEN-LAST:event_btnLogoutMouseReleased

    private void panelMedicamentosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMedicamentosMouseReleased
        configurarPanelBotones("Control de medicamentos", null, null, null, null, "Medicamento");
        panelBotones.configurarTabla();
        panelBotones.setDisplay("datos del medicamento");
        mostrarControl(false);
        mostrarPanel(true);
    }//GEN-LAST:event_panelMedicamentosMouseReleased

    private void rptFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptFarmaciaActionPerformed
        Reportador.verReporte("Farmacia");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptFarmaciaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        menuReportes.doClick();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistasActionPerformed
        menuVistas.doClick();
    }//GEN-LAST:event_btnVistasActionPerformed

    private void rptMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptMedicoActionPerformed
        Reportador.verReporte("Medico");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento...", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptMedicoActionPerformed

    private void rptPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptPacienteActionPerformed
        Reportador.verReporte("Paciente");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento...", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptPacienteActionPerformed

    private void rptFarmaceuticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptFarmaceuticasActionPerformed
        Reportador.verReporte("Farmaceutica");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento...", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptFarmaceuticasActionPerformed

    private void rptRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptRecetasActionPerformed
        Reportador.verReporte("Receta");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento...", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptRecetasActionPerformed

    private void rptInventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptInventariosActionPerformed
        Reportador.verReporte("Inventario");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento...", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptInventariosActionPerformed

    private void rptContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptContratosActionPerformed
        Reportador.verReporte("Contrato");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento...", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptContratosActionPerformed

    private void rptMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptMedicamentosActionPerformed
        Reportador.verReporte("Medicamento");
        JOptionPane.showMessageDialog(this, "Generando reporte, espere un momento...", "Generando reporte", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rptMedicamentosActionPerformed

    private void viewSupervisoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupervisoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSupervisoresActionPerformed

    private void chartDemandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartDemandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chartDemandaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    private Usuario user;
    private PanelBotones panelBotones;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnPrincipal;
    private javax.swing.JButton btnReportes;
    private javax.swing.JPanel btnUsuarios;
    private javax.swing.JButton btnVistas;
    private javax.swing.JMenuItem chartDemanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JMenu menuEstadisticas;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuVistas;
    private javax.swing.JPanel panelContratos;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelFarmaceuticas;
    private javax.swing.JPanel panelFarmacias;
    private javax.swing.JPanel panelInventarios;
    private javax.swing.JPanel panelMedicamentos;
    private javax.swing.JPanel panelMedicos;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JPanel panelRecetas;
    private javax.swing.JPanel panelRoot;
    private javax.swing.JMenuItem rptContratos;
    private javax.swing.JMenuItem rptFarmaceuticas;
    private javax.swing.JMenuItem rptFarmacia;
    private javax.swing.JMenuItem rptInventarios;
    private javax.swing.JMenuItem rptMedicamentos;
    private javax.swing.JMenuItem rptMedico;
    private javax.swing.JMenuItem rptPaciente;
    private javax.swing.JMenuItem rptRecetas;
    private javax.swing.JLabel txtFarmaceuticas2;
    private javax.swing.JLabel txtFarmacias;
    private javax.swing.JLabel txtMedicos;
    private javax.swing.JLabel txtPacientes;
    private javax.swing.JLabel txtRecetas;
    private javax.swing.JLabel txtRecetas1;
    private javax.swing.JLabel txtRecetas2;
    private javax.swing.JLabel txtRecetas3;
    private javax.swing.JLabel txtRecetas4;
    private javax.swing.JLabel txtRecetas5;
    private javax.swing.JMenuItem viewSupervisores;
    // End of variables declaration//GEN-END:variables
}
